### ISSUE TITLE
Error on deploying

### ISSUE THREAD

**Issue by vijmen** [apigee/openbank#88]
Hi
I receive the following error on running gulp. Can someone please help with this?

$ node -v
v8.9.4

$ gulp openbankdeploy --env test
[13:28:05] Using gulpfile ****/openbank/gulpfile.js
[13:28:05] Starting 'openbankdeploy'...
[13:28:05] 'openbankdeploy' errored after 2.84 ms
[13:28:05] TypeError: gulp.on(...).on(...).on(...).on(...).start is not a function
    at ****/openbank/node_modules/gulp-sequence/index.js:66:12
    at apply (****/openbank/node_modules/thunks/index.js:354:38)
    at tryRun (****/openbank/node_modules/thunks/index.js:224:19)
    at runThunk (****/openbank/node_modules/thunks/index.js:217:15)
    at ****/openbank/node_modules/thunks/index.js:314:49
    at apply (****/openbank/node_modules/thunks/index.js:354:38)
    at tryRun (****/openbank/node_modules/thunks/index.js:224:19)
    at runThunk (****/openbank/node_modules/thunks/index.js:217:15)
    at continuation (****/openbank/node_modules/thunks/index.js:164:10)
    at child (****/openbank/node_modules/thunks/index.js:155:24)
    at thunkFunction (****/openbank/node_modules/thunks/index.js:145:14)
    at gulpSequence (****/openbank/node_modules/gulp-sequence/index.js:70:19)
    at ****/openbank/gulpfile.js:128:3
    at taskWrapper (****/openbank/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)

**Comment by rohan-m** [comment]
Can you please try with downgrading the node version. This often seem to happen with node v10.
If that doesnt work, can you please provide the node, npm and gulp versions

**Comment by frank-martinez** [comment]
I've exactly the same error. My versions are the next:
frank@frank-VirtualBox:~/openbank$ uname -a
Linux frank-VirtualBox 4.15.0-38-generic #41~16.04.1-Ubuntu SMP Wed Oct 10 20:16:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
frank@frank-VirtualBox:~/openbank$ npm version
{ 'apigee-openbank': '1.0.1',
  npm: '5.6.0',
  ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '3',
  nghttp2: '1.32.0',
  node: '8.11.4',
  openssl: '1.0.2p',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.19.1',
  v8: '6.2.414.54',
  zlib: '1.2.11' }

Any idea would be appreciated!!

**Comment by frank-martinez** [comment]
frank@frank-VirtualBox:~/openbank$ gulp -v
[11:38:42] CLI version 1.2.2
[11:38:42] Local version 4.0.0

**Comment by bungandy** [comment]
Hi, try to remove old gulp and install `yarn add gulp@3.9.1 --dev`

**Comment by laughingbiscuit** [comment]
Closing as the project has been refactored and this bug issue no longer applies - please see https://github.com/apigee/openbank#previous-versions
